apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: teamcity-agent-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teamcity-agent
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80