kind: Deployment
apiVersion: apps/v1
metadata:
  name: teamcity
spec:
  replicas:  1
  selector:
    matchLabels:
      app: teamcity
  template:
    metadata:
      labels:
        app: teamcity
    spec:
      containers:
        - name: teamcity
          image: jetbrains/teamcity-server
          ports:
            - name: teamcity
              containerPort: 8111
          volumeMounts:
            - name:  teamcity-data
              mountPath: /var/lib/teamcity
          resources: 
            limits:
              cpu: 800m
              memory: 968Mi
            requests:
              cpu: 600m
              memory: 968Mi
      volumes:
      - name: "teamcity-data"
        persistentVolumeClaim:
          claimName: "teamcity-data"
      nodeSelector:
        nodetype: server
