kind: Deployment
apiVersion: apps/v1
metadata:
  name: teamcity-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: teamcity-agent
  template:
    metadata:
      labels:
        app: teamcity-agent
    spec:
      containers:
        - name: teamcityagent
          image: jetbrains/teamcity-agent
          env:
            - name: SERVER_URL
              value: http://teamcity:443
          volumeMounts:
            - name:  agent-data
              mountPath: /data
          resources:
            limits:
              cpu: 100m
              memory: 400Mi
            requests:
              cpu: 100m
              memory: 300Mi
      volumes:
          - name: agent-data
            hostPath:
                path: /var/buildAgent
      nodeSelector:
        nodetype: agent
