apiVersion: v1
kind: Service
metadata:
  name: teamcity
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-2:208862446705:certificate/b6938c7f-48e7-4f10-9168-352605acb34d"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  selector:
    app: teamcity
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8111